name: flightlogbook
description: Flight Logbook application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.3+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:
  intl_translation:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # https://pub.dev/packages/cupertino_icons
  cupertino_icons: ^0.1.3

  # https://pub.dev/packages/font_awesome_flutter
  font_awesome_flutter: ^8.7.0

  # https://pub.dev/packages/flutter_bloc
  equatable: ^1.1.1

  # https://pub.dev/packages/flutter_bloc
  flutter_bloc: ^3.2.0

  # https://pub.dev/packages/cloud_firestore
  cloud_firestore: ^0.13.4+1

  # https://pub.dev/packages/firebase_auth
  # DO NOT ADD ^ since it causes "UserAgent.h not found error on ios build" (as of 0.15.5+2)
  firebase_auth: 0.15.4

  # https://pub.dev/packages/google_sign_in
  google_sign_in: ^4.1.4

  # https://pub.dev/packages/firebase_core
  # DO NOT ADD ^ since it causes "UserAgent.h not found error on ios build" (as of 0.4.4+2)
  firebase_core: 0.4.4

  # https://pub.dev/packages/awesome_dialog
  awesome_dialog: ^0.1.3

  # https://pub.dev/packages/flutter_slidable
  flutter_slidable: ^0.5.4

  # https://pub.dev/packages/shared_preferences
  shared_preferences: ^0.5.6+3

  # https://pub.dev/packages/prefs_config
  prefs_config: ^0.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:

  # https://pub.dev/packages/mockito
  mockito: ^4.1.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
